version: '3'

services:
  goose:
    build: .
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - mysql
    environment:
      - GOOSE_DRIVER=mysql
      - GOOSE_DBSTRING=goose:goose@tcp(mysql:3306)/testdb
    networks:
      - goose-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=goose
      - MYSQL_PASSWORD=goose
      - MYSQL_DATABASE=testdb
    ports:
      - "3906:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - goose-network

volumes:
  mysql-data:

networks:
  goose-network:
    driver: bridge
